[build]
  command = "pnpm install && pnpm build"
  publish = "frontend/dist"
  functions = "." # Because api.js is at root

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
