
[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "pnpm install --prefix ../backend && pnpm install && pnpm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
